<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class StatusBase extends MagratheaModel implements iMagratheaModel {

	public $id, $title;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "status";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["title"] = "string";

		$this->relations["properties"]["Tasks"] = null;
		$this->relations["methods"]["Tasks"] = "GetTasks";
		$this->relations["lazyload"]["Tasks"] = "true";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";

	}

	// >>> relations:
	public function GetTasks(){
		if($this->relations["properties"]["Tasks"] != null) return $this->relations["properties"]["Tasks"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Tasks"] = TaskControlBase::GetWhere(array("status_id" => $this->$pk));
		return $this->relations["properties"]["Tasks"];
	}

}

class StatusControlBase extends MagratheaModelControl {
	protected static $modelName = "Status";
	protected static $dbTable = "status";
}
?>